/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrepararRouteImport } from './routes/preparar'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PilaresRouteImport } from './routes/pilares'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as IdiomaRouteImport } from './routes/idioma'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as CirculosIndexRouteImport } from './routes/circulos.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as PilarSlugRouteImport } from './routes/pilar.$slug'
import { Route as PagamentoSucessoRouteImport } from './routes/pagamento.sucesso'
import { Route as PagamentoLiberadoRouteImport } from './routes/pagamento.liberado'
import { Route as PagamentoConfirmandoRouteImport } from './routes/pagamento.confirmando'
import { Route as OnboardingProntoRouteImport } from './routes/onboarding.pronto'
import { Route as ModuloSlugRouteImport } from './routes/modulo.$slug'
import { Route as CirculosIdRouteImport } from './routes/circulos.$id'
import { Route as CheckoutStripeRouteImport } from './routes/checkout.stripe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout.retorno'
import { Route as ApiOnboardingChatRouteImport } from './routes/api/onboarding-chat'
import { Route as ApiMentorRouteImport } from './routes/api/mentor'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedResumoSemanalRouteImport } from './routes/_authenticated/resumo-semanal'
import { Route as AuthenticatedPreferenciasNotificacoesRouteImport } from './routes/_authenticated/preferencias-notificacoes'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedMeuDiaRouteImport } from './routes/_authenticated/meu-dia'
import { Route as AuthenticatedMetasRecebidasRouteImport } from './routes/_authenticated/metas-recebidas'
import { Route as AuthenticatedMemoriaRouteImport } from './routes/_authenticated/memoria'
import { Route as AuthenticatedMagnetosRouteImport } from './routes/_authenticated/magnetos'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedImpactoRouteImport } from './routes/_authenticated/impacto'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedDirecoesSalvasRouteImport } from './routes/_authenticated/direcoes-salvas'
import { Route as AuthenticatedDirecoesRouteImport } from './routes/_authenticated/direcoes'
import { Route as AuthenticatedDinheiroRouteImport } from './routes/_authenticated/dinheiro'
import { Route as AuthenticatedCirculoRouteImport } from './routes/_authenticated/circulo'
import { Route as AuthenticatedCampoMagneticoRouteImport } from './routes/_authenticated/campo-magnetico'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedAtividadeRouteImport } from './routes/_authenticated/atividade'
import { Route as AuthenticatedAplicarDirecaoRouteImport } from './routes/_authenticated/aplicar-direcao'
import { Route as AuthenticatedAntenasRouteImport } from './routes/_authenticated/antenas'
import { Route as ApiPublicStripeE2eRouteImport } from './routes/api/public/stripe-e2e'
import { Route as AuthenticatedMetaIdRouteImport } from './routes/_authenticated/meta.$id'
import { Route as AuthenticatedFerramentasWhatsappRouteImport } from './routes/_authenticated/ferramentas.whatsapp'
import { Route as AuthenticatedFerramentasPlannerRouteImport } from './routes/_authenticated/ferramentas.planner'
import { Route as AuthenticatedFerramentasMetaReceitaRouteImport } from './routes/_authenticated/ferramentas.meta-receita'
import { Route as AuthenticatedFerramentasDiagnosticoRouteImport } from './routes/_authenticated/ferramentas.diagnostico'
import { Route as AuthenticatedFerramentasConteudoRouteImport } from './routes/_authenticated/ferramentas.conteudo'
import { Route as AuthenticatedFerramentasChecklistRouteImport } from './routes/_authenticated/ferramentas.checklist'
import { Route as AuthenticatedAdminSuporteRouteImport } from './routes/_authenticated/admin.suporte'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedAdminPodcastsRouteImport } from './routes/_authenticated/admin.podcasts'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminEmbaixadoresRouteImport } from './routes/_authenticated/admin.embaixadores'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsInfinitepayWebhookRouteImport } from './routes/api/public/payments/infinitepay-webhook'
import { Route as ApiPublicNotificationsOpenedRouteImport } from './routes/api/public/notifications/opened'
import { Route as ApiPublicCronReleaseCommissionsRouteImport } from './routes/api/public/cron/release-commissions'
import { Route as ApiPublicCronMarkUnconvertedReferralsRouteImport } from './routes/api/public/cron/mark-unconverted-referrals'
import { Route as ApiPublicCronMagNotificationsRouteImport } from './routes/api/public/cron/mag-notifications'
import { Route as ApiPublicPaymentsWebhookStripeRouteImport } from './routes/api/public/payments/webhook.stripe'
import { Route as ApiPublicPaymentsWebhookProviderRouteImport } from './routes/api/public/payments/webhook.$provider'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepararRoute = PrepararRouteImport.update({
  id: '/preparar',
  path: '/preparar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PilaresRoute = PilaresRouteImport.update({
  id: '/pilares',
  path: '/pilares',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomaRoute = IdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const CirculosIndexRoute = CirculosIndexRouteImport.update({
  id: '/circulos/',
  path: '/circulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PilarSlugRoute = PilarSlugRouteImport.update({
  id: '/pilar/$slug',
  path: '/pilar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoSucessoRoute = PagamentoSucessoRouteImport.update({
  id: '/pagamento/sucesso',
  path: '/pagamento/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoLiberadoRoute = PagamentoLiberadoRouteImport.update({
  id: '/pagamento/liberado',
  path: '/pagamento/liberado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmandoRoute = PagamentoConfirmandoRouteImport.update({
  id: '/pagamento/confirmando',
  path: '/pagamento/confirmando',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProntoRoute = OnboardingProntoRouteImport.update({
  id: '/pronto',
  path: '/pronto',
  getParentRoute: () => OnboardingRoute,
} as any)
const ModuloSlugRoute = ModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CirculosIdRoute = CirculosIdRouteImport.update({
  id: '/circulos/$id',
  path: '/circulos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutStripeRoute = CheckoutStripeRouteImport.update({
  id: '/stripe',
  path: '/stripe',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiOnboardingChatRoute = ApiOnboardingChatRouteImport.update({
  id: '/api/onboarding-chat',
  path: '/api/onboarding-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRoute = ApiMentorRouteImport.update({
  id: '/api/mentor',
  path: '/api/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumoSemanalRoute =
  AuthenticatedResumoSemanalRouteImport.update({
    id: '/resumo-semanal',
    path: '/resumo-semanal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreferenciasNotificacoesRoute =
  AuthenticatedPreferenciasNotificacoesRouteImport.update({
    id: '/preferencias-notificacoes',
    path: '/preferencias-notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuDiaRoute = AuthenticatedMeuDiaRouteImport.update({
  id: '/meu-dia',
  path: '/meu-dia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRecebidasRoute =
  AuthenticatedMetasRecebidasRouteImport.update({
    id: '/metas-recebidas',
    path: '/metas-recebidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemoriaRoute = AuthenticatedMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMagnetosRoute = AuthenticatedMagnetosRouteImport.update({
  id: '/magnetos',
  path: '/magnetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpactoRoute = AuthenticatedImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirecoesSalvasRoute =
  AuthenticatedDirecoesSalvasRouteImport.update({
    id: '/direcoes-salvas',
    path: '/direcoes-salvas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirecoesRoute = AuthenticatedDirecoesRouteImport.update({
  id: '/direcoes',
  path: '/direcoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDinheiroRoute = AuthenticatedDinheiroRouteImport.update({
  id: '/dinheiro',
  path: '/dinheiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirculoRoute = AuthenticatedCirculoRouteImport.update({
  id: '/circulo',
  path: '/circulo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampoMagneticoRoute =
  AuthenticatedCampoMagneticoRouteImport.update({
    id: '/campo-magnetico',
    path: '/campo-magnetico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadeRoute = AuthenticatedAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAplicarDirecaoRoute =
  AuthenticatedAplicarDirecaoRouteImport.update({
    id: '/aplicar-direcao',
    path: '/aplicar-direcao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAntenasRoute = AuthenticatedAntenasRouteImport.update({
  id: '/antenas',
  path: '/antenas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeE2eRoute = ApiPublicStripeE2eRouteImport.update({
  id: '/api/public/stripe-e2e',
  path: '/api/public/stripe-e2e',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMetaIdRoute = AuthenticatedMetaIdRouteImport.update({
  id: '/meta/$id',
  path: '/meta/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerramentasWhatsappRoute =
  AuthenticatedFerramentasWhatsappRouteImport.update({
    id: '/ferramentas/whatsapp',
    path: '/ferramentas/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasPlannerRoute =
  AuthenticatedFerramentasPlannerRouteImport.update({
    id: '/ferramentas/planner',
    path: '/ferramentas/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasMetaReceitaRoute =
  AuthenticatedFerramentasMetaReceitaRouteImport.update({
    id: '/ferramentas/meta-receita',
    path: '/ferramentas/meta-receita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasDiagnosticoRoute =
  AuthenticatedFerramentasDiagnosticoRouteImport.update({
    id: '/ferramentas/diagnostico',
    path: '/ferramentas/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasConteudoRoute =
  AuthenticatedFerramentasConteudoRouteImport.update({
    id: '/ferramentas/conteudo',
    path: '/ferramentas/conteudo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasChecklistRoute =
  AuthenticatedFerramentasChecklistRouteImport.update({
    id: '/ferramentas/checklist',
    path: '/ferramentas/checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSuporteRoute =
  AuthenticatedAdminSuporteRouteImport.update({
    id: '/admin/suporte',
    path: '/admin/suporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/admin/referrals',
    path: '/admin/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPodcastsRoute =
  AuthenticatedAdminPodcastsRouteImport.update({
    id: '/admin/podcasts',
    path: '/admin/podcasts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/admin/notificacoes',
    path: '/admin/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmbaixadoresRoute =
  AuthenticatedAdminEmbaixadoresRouteImport.update({
    id: '/admin/embaixadores',
    path: '/admin/embaixadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsInfinitepayWebhookRoute =
  ApiPublicPaymentsInfinitepayWebhookRouteImport.update({
    id: '/api/public/payments/infinitepay-webhook',
    path: '/api/public/payments/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationsOpenedRoute =
  ApiPublicNotificationsOpenedRouteImport.update({
    id: '/api/public/notifications/opened',
    path: '/api/public/notifications/opened',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReleaseCommissionsRoute =
  ApiPublicCronReleaseCommissionsRouteImport.update({
    id: '/api/public/cron/release-commissions',
    path: '/api/public/cron/release-commissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMarkUnconvertedReferralsRoute =
  ApiPublicCronMarkUnconvertedReferralsRouteImport.update({
    id: '/api/public/cron/mark-unconverted-referrals',
    path: '/api/public/cron/mark-unconverted-referrals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMagNotificationsRoute =
  ApiPublicCronMagNotificationsRouteImport.update({
    id: '/api/public/cron/mag-notifications',
    path: '/api/public/cron/mag-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookStripeRoute =
  ApiPublicPaymentsWebhookStripeRouteImport.update({
    id: '/api/public/payments/webhook/stripe',
    path: '/api/public/payments/webhook/stripe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookProviderRoute =
  ApiPublicPaymentsWebhookProviderRouteImport.update({
    id: '/api/public/payments/webhook/$provider',
    path: '/api/public/payments/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/idioma': typeof IdiomaRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pilares': typeof PilaresRoute
  '/planos': typeof PlanosRoute
  '/preparar': typeof PrepararRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/antenas': typeof AuthenticatedAntenasRoute
  '/aplicar-direcao': typeof AuthenticatedAplicarDirecaoRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/campo-magnetico': typeof AuthenticatedCampoMagneticoRoute
  '/circulo': typeof AuthenticatedCirculoRoute
  '/dinheiro': typeof AuthenticatedDinheiroRoute
  '/direcoes': typeof AuthenticatedDirecoesRoute
  '/direcoes-salvas': typeof AuthenticatedDirecoesSalvasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/impacto': typeof AuthenticatedImpactoRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/magnetos': typeof AuthenticatedMagnetosRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/metas-recebidas': typeof AuthenticatedMetasRecebidasRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/preferencias-notificacoes': typeof AuthenticatedPreferenciasNotificacoesRoute
  '/resumo-semanal': typeof AuthenticatedResumoSemanalRoute
  '/status': typeof AuthenticatedStatusRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/onboarding-chat': typeof ApiOnboardingChatRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/stripe': typeof CheckoutStripeRoute
  '/circulos/$id': typeof CirculosIdRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/pagamento/confirmando': typeof PagamentoConfirmandoRoute
  '/pagamento/liberado': typeof PagamentoLiberadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/pilar/$slug': typeof PilarSlugRoute
  '/r/$code': typeof RCodeRoute
  '/circulos/': typeof CirculosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/admin/embaixadores': typeof AuthenticatedAdminEmbaixadoresRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/ferramentas/checklist': typeof AuthenticatedFerramentasChecklistRoute
  '/ferramentas/conteudo': typeof AuthenticatedFerramentasConteudoRoute
  '/ferramentas/diagnostico': typeof AuthenticatedFerramentasDiagnosticoRoute
  '/ferramentas/meta-receita': typeof AuthenticatedFerramentasMetaReceitaRoute
  '/ferramentas/planner': typeof AuthenticatedFerramentasPlannerRoute
  '/ferramentas/whatsapp': typeof AuthenticatedFerramentasWhatsappRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/api/public/stripe-e2e': typeof ApiPublicStripeE2eRoute
  '/api/public/cron/mag-notifications': typeof ApiPublicCronMagNotificationsRoute
  '/api/public/cron/mark-unconverted-referrals': typeof ApiPublicCronMarkUnconvertedReferralsRoute
  '/api/public/cron/release-commissions': typeof ApiPublicCronReleaseCommissionsRoute
  '/api/public/notifications/opened': typeof ApiPublicNotificationsOpenedRoute
  '/api/public/payments/infinitepay-webhook': typeof ApiPublicPaymentsInfinitepayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/idioma': typeof IdiomaRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pilares': typeof PilaresRoute
  '/planos': typeof PlanosRoute
  '/preparar': typeof PrepararRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/antenas': typeof AuthenticatedAntenasRoute
  '/aplicar-direcao': typeof AuthenticatedAplicarDirecaoRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/campo-magnetico': typeof AuthenticatedCampoMagneticoRoute
  '/circulo': typeof AuthenticatedCirculoRoute
  '/dinheiro': typeof AuthenticatedDinheiroRoute
  '/direcoes': typeof AuthenticatedDirecoesRoute
  '/direcoes-salvas': typeof AuthenticatedDirecoesSalvasRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/impacto': typeof AuthenticatedImpactoRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/magnetos': typeof AuthenticatedMagnetosRoute
  '/memoria': typeof AuthenticatedMemoriaRoute
  '/metas-recebidas': typeof AuthenticatedMetasRecebidasRoute
  '/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/preferencias-notificacoes': typeof AuthenticatedPreferenciasNotificacoesRoute
  '/resumo-semanal': typeof AuthenticatedResumoSemanalRoute
  '/status': typeof AuthenticatedStatusRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/onboarding-chat': typeof ApiOnboardingChatRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/stripe': typeof CheckoutStripeRoute
  '/circulos/$id': typeof CirculosIdRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/pagamento/confirmando': typeof PagamentoConfirmandoRoute
  '/pagamento/liberado': typeof PagamentoLiberadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/pilar/$slug': typeof PilarSlugRoute
  '/r/$code': typeof RCodeRoute
  '/circulos': typeof CirculosIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/admin/embaixadores': typeof AuthenticatedAdminEmbaixadoresRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/ferramentas/checklist': typeof AuthenticatedFerramentasChecklistRoute
  '/ferramentas/conteudo': typeof AuthenticatedFerramentasConteudoRoute
  '/ferramentas/diagnostico': typeof AuthenticatedFerramentasDiagnosticoRoute
  '/ferramentas/meta-receita': typeof AuthenticatedFerramentasMetaReceitaRoute
  '/ferramentas/planner': typeof AuthenticatedFerramentasPlannerRoute
  '/ferramentas/whatsapp': typeof AuthenticatedFerramentasWhatsappRoute
  '/meta/$id': typeof AuthenticatedMetaIdRoute
  '/api/public/stripe-e2e': typeof ApiPublicStripeE2eRoute
  '/api/public/cron/mag-notifications': typeof ApiPublicCronMagNotificationsRoute
  '/api/public/cron/mark-unconverted-referrals': typeof ApiPublicCronMarkUnconvertedReferralsRoute
  '/api/public/cron/release-commissions': typeof ApiPublicCronReleaseCommissionsRoute
  '/api/public/notifications/opened': typeof ApiPublicNotificationsOpenedRoute
  '/api/public/payments/infinitepay-webhook': typeof ApiPublicPaymentsInfinitepayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/assinar': typeof AssinarRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/idioma': typeof IdiomaRoute
  '/mentor': typeof MentorRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pilares': typeof PilaresRoute
  '/planos': typeof PlanosRoute
  '/preparar': typeof PrepararRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/antenas': typeof AuthenticatedAntenasRoute
  '/_authenticated/aplicar-direcao': typeof AuthenticatedAplicarDirecaoRoute
  '/_authenticated/atividade': typeof AuthenticatedAtividadeRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/campo-magnetico': typeof AuthenticatedCampoMagneticoRoute
  '/_authenticated/circulo': typeof AuthenticatedCirculoRoute
  '/_authenticated/dinheiro': typeof AuthenticatedDinheiroRoute
  '/_authenticated/direcoes': typeof AuthenticatedDirecoesRoute
  '/_authenticated/direcoes-salvas': typeof AuthenticatedDirecoesSalvasRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/impacto': typeof AuthenticatedImpactoRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/magnetos': typeof AuthenticatedMagnetosRoute
  '/_authenticated/memoria': typeof AuthenticatedMemoriaRoute
  '/_authenticated/metas-recebidas': typeof AuthenticatedMetasRecebidasRoute
  '/_authenticated/meu-dia': typeof AuthenticatedMeuDiaRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/preferencias-notificacoes': typeof AuthenticatedPreferenciasNotificacoesRoute
  '/_authenticated/resumo-semanal': typeof AuthenticatedResumoSemanalRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/onboarding-chat': typeof ApiOnboardingChatRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/stripe': typeof CheckoutStripeRoute
  '/circulos/$id': typeof CirculosIdRoute
  '/modulo/$slug': typeof ModuloSlugRoute
  '/onboarding/pronto': typeof OnboardingProntoRoute
  '/pagamento/confirmando': typeof PagamentoConfirmandoRoute
  '/pagamento/liberado': typeof PagamentoLiberadoRoute
  '/pagamento/sucesso': typeof PagamentoSucessoRoute
  '/pilar/$slug': typeof PilarSlugRoute
  '/r/$code': typeof RCodeRoute
  '/circulos/': typeof CirculosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/_authenticated/admin/embaixadores': typeof AuthenticatedAdminEmbaixadoresRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/podcasts': typeof AuthenticatedAdminPodcastsRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRoute
  '/_authenticated/ferramentas/checklist': typeof AuthenticatedFerramentasChecklistRoute
  '/_authenticated/ferramentas/conteudo': typeof AuthenticatedFerramentasConteudoRoute
  '/_authenticated/ferramentas/diagnostico': typeof AuthenticatedFerramentasDiagnosticoRoute
  '/_authenticated/ferramentas/meta-receita': typeof AuthenticatedFerramentasMetaReceitaRoute
  '/_authenticated/ferramentas/planner': typeof AuthenticatedFerramentasPlannerRoute
  '/_authenticated/ferramentas/whatsapp': typeof AuthenticatedFerramentasWhatsappRoute
  '/_authenticated/meta/$id': typeof AuthenticatedMetaIdRoute
  '/api/public/stripe-e2e': typeof ApiPublicStripeE2eRoute
  '/api/public/cron/mag-notifications': typeof ApiPublicCronMagNotificationsRoute
  '/api/public/cron/mark-unconverted-referrals': typeof ApiPublicCronMarkUnconvertedReferralsRoute
  '/api/public/cron/release-commissions': typeof ApiPublicCronReleaseCommissionsRoute
  '/api/public/notifications/opened': typeof ApiPublicNotificationsOpenedRoute
  '/api/public/payments/infinitepay-webhook': typeof ApiPublicPaymentsInfinitepayWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/assinar'
    | '/auth'
    | '/checkout'
    | '/configuracoes'
    | '/ferramentas'
    | '/idioma'
    | '/mentor'
    | '/onboarding'
    | '/pilares'
    | '/planos'
    | '/preparar'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/antenas'
    | '/aplicar-direcao'
    | '/atividade'
    | '/buscar'
    | '/campo-magnetico'
    | '/circulo'
    | '/dinheiro'
    | '/direcoes'
    | '/direcoes-salvas'
    | '/favoritos'
    | '/historico'
    | '/impacto'
    | '/jornada'
    | '/magnetos'
    | '/memoria'
    | '/metas-recebidas'
    | '/meu-dia'
    | '/notas'
    | '/notificacoes'
    | '/perfil'
    | '/planejamento'
    | '/preferencias-notificacoes'
    | '/resumo-semanal'
    | '/status'
    | '/suporte'
    | '/api/mentor'
    | '/api/onboarding-chat'
    | '/checkout/retorno'
    | '/checkout/return'
    | '/checkout/stripe'
    | '/circulos/$id'
    | '/modulo/$slug'
    | '/onboarding/pronto'
    | '/pagamento/confirmando'
    | '/pagamento/liberado'
    | '/pagamento/sucesso'
    | '/pilar/$slug'
    | '/r/$code'
    | '/circulos/'
    | '/ferramentas/'
    | '/admin/embaixadores'
    | '/admin/notificacoes'
    | '/admin/payments'
    | '/admin/podcasts'
    | '/admin/referrals'
    | '/admin/suporte'
    | '/ferramentas/checklist'
    | '/ferramentas/conteudo'
    | '/ferramentas/diagnostico'
    | '/ferramentas/meta-receita'
    | '/ferramentas/planner'
    | '/ferramentas/whatsapp'
    | '/meta/$id'
    | '/api/public/stripe-e2e'
    | '/api/public/cron/mag-notifications'
    | '/api/public/cron/mark-unconverted-referrals'
    | '/api/public/cron/release-commissions'
    | '/api/public/notifications/opened'
    | '/api/public/payments/infinitepay-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/payments/webhook/$provider'
    | '/api/public/payments/webhook/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/assinar'
    | '/auth'
    | '/checkout'
    | '/configuracoes'
    | '/idioma'
    | '/mentor'
    | '/onboarding'
    | '/pilares'
    | '/planos'
    | '/preparar'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/antenas'
    | '/aplicar-direcao'
    | '/atividade'
    | '/buscar'
    | '/campo-magnetico'
    | '/circulo'
    | '/dinheiro'
    | '/direcoes'
    | '/direcoes-salvas'
    | '/favoritos'
    | '/historico'
    | '/impacto'
    | '/jornada'
    | '/magnetos'
    | '/memoria'
    | '/metas-recebidas'
    | '/meu-dia'
    | '/notas'
    | '/notificacoes'
    | '/perfil'
    | '/planejamento'
    | '/preferencias-notificacoes'
    | '/resumo-semanal'
    | '/status'
    | '/suporte'
    | '/api/mentor'
    | '/api/onboarding-chat'
    | '/checkout/retorno'
    | '/checkout/return'
    | '/checkout/stripe'
    | '/circulos/$id'
    | '/modulo/$slug'
    | '/onboarding/pronto'
    | '/pagamento/confirmando'
    | '/pagamento/liberado'
    | '/pagamento/sucesso'
    | '/pilar/$slug'
    | '/r/$code'
    | '/circulos'
    | '/ferramentas'
    | '/admin/embaixadores'
    | '/admin/notificacoes'
    | '/admin/payments'
    | '/admin/podcasts'
    | '/admin/referrals'
    | '/admin/suporte'
    | '/ferramentas/checklist'
    | '/ferramentas/conteudo'
    | '/ferramentas/diagnostico'
    | '/ferramentas/meta-receita'
    | '/ferramentas/planner'
    | '/ferramentas/whatsapp'
    | '/meta/$id'
    | '/api/public/stripe-e2e'
    | '/api/public/cron/mag-notifications'
    | '/api/public/cron/mark-unconverted-referrals'
    | '/api/public/cron/release-commissions'
    | '/api/public/notifications/opened'
    | '/api/public/payments/infinitepay-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/payments/webhook/$provider'
    | '/api/public/payments/webhook/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/assinar'
    | '/auth'
    | '/checkout'
    | '/configuracoes'
    | '/ferramentas'
    | '/idioma'
    | '/mentor'
    | '/onboarding'
    | '/pilares'
    | '/planos'
    | '/preparar'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/antenas'
    | '/_authenticated/aplicar-direcao'
    | '/_authenticated/atividade'
    | '/_authenticated/buscar'
    | '/_authenticated/campo-magnetico'
    | '/_authenticated/circulo'
    | '/_authenticated/dinheiro'
    | '/_authenticated/direcoes'
    | '/_authenticated/direcoes-salvas'
    | '/_authenticated/favoritos'
    | '/_authenticated/historico'
    | '/_authenticated/impacto'
    | '/_authenticated/jornada'
    | '/_authenticated/magnetos'
    | '/_authenticated/memoria'
    | '/_authenticated/metas-recebidas'
    | '/_authenticated/meu-dia'
    | '/_authenticated/notas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/planejamento'
    | '/_authenticated/preferencias-notificacoes'
    | '/_authenticated/resumo-semanal'
    | '/_authenticated/status'
    | '/_authenticated/suporte'
    | '/api/mentor'
    | '/api/onboarding-chat'
    | '/checkout/retorno'
    | '/checkout/return'
    | '/checkout/stripe'
    | '/circulos/$id'
    | '/modulo/$slug'
    | '/onboarding/pronto'
    | '/pagamento/confirmando'
    | '/pagamento/liberado'
    | '/pagamento/sucesso'
    | '/pilar/$slug'
    | '/r/$code'
    | '/circulos/'
    | '/ferramentas/'
    | '/_authenticated/admin/embaixadores'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/podcasts'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/ferramentas/checklist'
    | '/_authenticated/ferramentas/conteudo'
    | '/_authenticated/ferramentas/diagnostico'
    | '/_authenticated/ferramentas/meta-receita'
    | '/_authenticated/ferramentas/planner'
    | '/_authenticated/ferramentas/whatsapp'
    | '/_authenticated/meta/$id'
    | '/api/public/stripe-e2e'
    | '/api/public/cron/mag-notifications'
    | '/api/public/cron/mark-unconverted-referrals'
    | '/api/public/cron/release-commissions'
    | '/api/public/notifications/opened'
    | '/api/public/payments/infinitepay-webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/api/public/payments/webhook/$provider'
    | '/api/public/payments/webhook/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AssinarRoute: typeof AssinarRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FerramentasRoute: typeof FerramentasRouteWithChildren
  IdiomaRoute: typeof IdiomaRoute
  MentorRoute: typeof MentorRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PilaresRoute: typeof PilaresRoute
  PlanosRoute: typeof PlanosRoute
  PrepararRoute: typeof PrepararRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiMentorRoute: typeof ApiMentorRoute
  ApiOnboardingChatRoute: typeof ApiOnboardingChatRoute
  CirculosIdRoute: typeof CirculosIdRoute
  ModuloSlugRoute: typeof ModuloSlugRoute
  PagamentoConfirmandoRoute: typeof PagamentoConfirmandoRoute
  PagamentoLiberadoRoute: typeof PagamentoLiberadoRoute
  PagamentoSucessoRoute: typeof PagamentoSucessoRoute
  PilarSlugRoute: typeof PilarSlugRoute
  RCodeRoute: typeof RCodeRoute
  CirculosIndexRoute: typeof CirculosIndexRoute
  ApiPublicStripeE2eRoute: typeof ApiPublicStripeE2eRoute
  ApiPublicCronMagNotificationsRoute: typeof ApiPublicCronMagNotificationsRoute
  ApiPublicCronMarkUnconvertedReferralsRoute: typeof ApiPublicCronMarkUnconvertedReferralsRoute
  ApiPublicCronReleaseCommissionsRoute: typeof ApiPublicCronReleaseCommissionsRoute
  ApiPublicNotificationsOpenedRoute: typeof ApiPublicNotificationsOpenedRoute
  ApiPublicPaymentsInfinitepayWebhookRoute: typeof ApiPublicPaymentsInfinitepayWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  ApiPublicPaymentsWebhookProviderRoute: typeof ApiPublicPaymentsWebhookProviderRoute
  ApiPublicPaymentsWebhookStripeRoute: typeof ApiPublicPaymentsWebhookStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparar': {
      id: '/preparar'
      path: '/preparar'
      fullPath: '/preparar'
      preLoaderRoute: typeof PrepararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilares': {
      id: '/pilares'
      path: '/pilares'
      fullPath: '/pilares'
      preLoaderRoute: typeof PilaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioma': {
      id: '/idioma'
      path: '/idioma'
      fullPath: '/idioma'
      preLoaderRoute: typeof IdiomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/circulos/': {
      id: '/circulos/'
      path: '/circulos'
      fullPath: '/circulos/'
      preLoaderRoute: typeof CirculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilar/$slug': {
      id: '/pilar/$slug'
      path: '/pilar/$slug'
      fullPath: '/pilar/$slug'
      preLoaderRoute: typeof PilarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/sucesso': {
      id: '/pagamento/sucesso'
      path: '/pagamento/sucesso'
      fullPath: '/pagamento/sucesso'
      preLoaderRoute: typeof PagamentoSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/liberado': {
      id: '/pagamento/liberado'
      path: '/pagamento/liberado'
      fullPath: '/pagamento/liberado'
      preLoaderRoute: typeof PagamentoLiberadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/confirmando': {
      id: '/pagamento/confirmando'
      path: '/pagamento/confirmando'
      fullPath: '/pagamento/confirmando'
      preLoaderRoute: typeof PagamentoConfirmandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pronto': {
      id: '/onboarding/pronto'
      path: '/pronto'
      fullPath: '/onboarding/pronto'
      preLoaderRoute: typeof OnboardingProntoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/modulo/$slug': {
      id: '/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof ModuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulos/$id': {
      id: '/circulos/$id'
      path: '/circulos/$id'
      fullPath: '/circulos/$id'
      preLoaderRoute: typeof CirculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/stripe': {
      id: '/checkout/stripe'
      path: '/stripe'
      fullPath: '/checkout/stripe'
      preLoaderRoute: typeof CheckoutStripeRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/onboarding-chat': {
      id: '/api/onboarding-chat'
      path: '/api/onboarding-chat'
      fullPath: '/api/onboarding-chat'
      preLoaderRoute: typeof ApiOnboardingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor': {
      id: '/api/mentor'
      path: '/api/mentor'
      fullPath: '/api/mentor'
      preLoaderRoute: typeof ApiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumo-semanal': {
      id: '/_authenticated/resumo-semanal'
      path: '/resumo-semanal'
      fullPath: '/resumo-semanal'
      preLoaderRoute: typeof AuthenticatedResumoSemanalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferencias-notificacoes': {
      id: '/_authenticated/preferencias-notificacoes'
      path: '/preferencias-notificacoes'
      fullPath: '/preferencias-notificacoes'
      preLoaderRoute: typeof AuthenticatedPreferenciasNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-dia': {
      id: '/_authenticated/meu-dia'
      path: '/meu-dia'
      fullPath: '/meu-dia'
      preLoaderRoute: typeof AuthenticatedMeuDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas-recebidas': {
      id: '/_authenticated/metas-recebidas'
      path: '/metas-recebidas'
      fullPath: '/metas-recebidas'
      preLoaderRoute: typeof AuthenticatedMetasRecebidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memoria': {
      id: '/_authenticated/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AuthenticatedMemoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magnetos': {
      id: '/_authenticated/magnetos'
      path: '/magnetos'
      fullPath: '/magnetos'
      preLoaderRoute: typeof AuthenticatedMagnetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impacto': {
      id: '/_authenticated/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof AuthenticatedImpactoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/direcoes-salvas': {
      id: '/_authenticated/direcoes-salvas'
      path: '/direcoes-salvas'
      fullPath: '/direcoes-salvas'
      preLoaderRoute: typeof AuthenticatedDirecoesSalvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/direcoes': {
      id: '/_authenticated/direcoes'
      path: '/direcoes'
      fullPath: '/direcoes'
      preLoaderRoute: typeof AuthenticatedDirecoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dinheiro': {
      id: '/_authenticated/dinheiro'
      path: '/dinheiro'
      fullPath: '/dinheiro'
      preLoaderRoute: typeof AuthenticatedDinheiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circulo': {
      id: '/_authenticated/circulo'
      path: '/circulo'
      fullPath: '/circulo'
      preLoaderRoute: typeof AuthenticatedCirculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campo-magnetico': {
      id: '/_authenticated/campo-magnetico'
      path: '/campo-magnetico'
      fullPath: '/campo-magnetico'
      preLoaderRoute: typeof AuthenticatedCampoMagneticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividade': {
      id: '/_authenticated/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthenticatedAtividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aplicar-direcao': {
      id: '/_authenticated/aplicar-direcao'
      path: '/aplicar-direcao'
      fullPath: '/aplicar-direcao'
      preLoaderRoute: typeof AuthenticatedAplicarDirecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/antenas': {
      id: '/_authenticated/antenas'
      path: '/antenas'
      fullPath: '/antenas'
      preLoaderRoute: typeof AuthenticatedAntenasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-e2e': {
      id: '/api/public/stripe-e2e'
      path: '/api/public/stripe-e2e'
      fullPath: '/api/public/stripe-e2e'
      preLoaderRoute: typeof ApiPublicStripeE2eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meta/$id': {
      id: '/_authenticated/meta/$id'
      path: '/meta/$id'
      fullPath: '/meta/$id'
      preLoaderRoute: typeof AuthenticatedMetaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/whatsapp': {
      id: '/_authenticated/ferramentas/whatsapp'
      path: '/ferramentas/whatsapp'
      fullPath: '/ferramentas/whatsapp'
      preLoaderRoute: typeof AuthenticatedFerramentasWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/planner': {
      id: '/_authenticated/ferramentas/planner'
      path: '/ferramentas/planner'
      fullPath: '/ferramentas/planner'
      preLoaderRoute: typeof AuthenticatedFerramentasPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/meta-receita': {
      id: '/_authenticated/ferramentas/meta-receita'
      path: '/ferramentas/meta-receita'
      fullPath: '/ferramentas/meta-receita'
      preLoaderRoute: typeof AuthenticatedFerramentasMetaReceitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/diagnostico': {
      id: '/_authenticated/ferramentas/diagnostico'
      path: '/ferramentas/diagnostico'
      fullPath: '/ferramentas/diagnostico'
      preLoaderRoute: typeof AuthenticatedFerramentasDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/conteudo': {
      id: '/_authenticated/ferramentas/conteudo'
      path: '/ferramentas/conteudo'
      fullPath: '/ferramentas/conteudo'
      preLoaderRoute: typeof AuthenticatedFerramentasConteudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas/checklist': {
      id: '/_authenticated/ferramentas/checklist'
      path: '/ferramentas/checklist'
      fullPath: '/ferramentas/checklist'
      preLoaderRoute: typeof AuthenticatedFerramentasChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/admin/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/podcasts': {
      id: '/_authenticated/admin/podcasts'
      path: '/admin/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AuthenticatedAdminPodcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/admin/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/embaixadores': {
      id: '/_authenticated/admin/embaixadores'
      path: '/admin/embaixadores'
      fullPath: '/admin/embaixadores'
      preLoaderRoute: typeof AuthenticatedAdminEmbaixadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/infinitepay-webhook': {
      id: '/api/public/payments/infinitepay-webhook'
      path: '/api/public/payments/infinitepay-webhook'
      fullPath: '/api/public/payments/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/opened': {
      id: '/api/public/notifications/opened'
      path: '/api/public/notifications/opened'
      fullPath: '/api/public/notifications/opened'
      preLoaderRoute: typeof ApiPublicNotificationsOpenedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/release-commissions': {
      id: '/api/public/cron/release-commissions'
      path: '/api/public/cron/release-commissions'
      fullPath: '/api/public/cron/release-commissions'
      preLoaderRoute: typeof ApiPublicCronReleaseCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mark-unconverted-referrals': {
      id: '/api/public/cron/mark-unconverted-referrals'
      path: '/api/public/cron/mark-unconverted-referrals'
      fullPath: '/api/public/cron/mark-unconverted-referrals'
      preLoaderRoute: typeof ApiPublicCronMarkUnconvertedReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mag-notifications': {
      id: '/api/public/cron/mag-notifications'
      path: '/api/public/cron/mag-notifications'
      fullPath: '/api/public/cron/mag-notifications'
      preLoaderRoute: typeof ApiPublicCronMagNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/stripe': {
      id: '/api/public/payments/webhook/stripe'
      path: '/api/public/payments/webhook/stripe'
      fullPath: '/api/public/payments/webhook/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/$provider': {
      id: '/api/public/payments/webhook/$provider'
      path: '/api/public/payments/webhook/$provider'
      fullPath: '/api/public/payments/webhook/$provider'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAntenasRoute: typeof AuthenticatedAntenasRoute
  AuthenticatedAplicarDirecaoRoute: typeof AuthenticatedAplicarDirecaoRoute
  AuthenticatedAtividadeRoute: typeof AuthenticatedAtividadeRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCampoMagneticoRoute: typeof AuthenticatedCampoMagneticoRoute
  AuthenticatedCirculoRoute: typeof AuthenticatedCirculoRoute
  AuthenticatedDinheiroRoute: typeof AuthenticatedDinheiroRoute
  AuthenticatedDirecoesRoute: typeof AuthenticatedDirecoesRoute
  AuthenticatedDirecoesSalvasRoute: typeof AuthenticatedDirecoesSalvasRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImpactoRoute: typeof AuthenticatedImpactoRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedMagnetosRoute: typeof AuthenticatedMagnetosRoute
  AuthenticatedMemoriaRoute: typeof AuthenticatedMemoriaRoute
  AuthenticatedMetasRecebidasRoute: typeof AuthenticatedMetasRecebidasRoute
  AuthenticatedMeuDiaRoute: typeof AuthenticatedMeuDiaRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPreferenciasNotificacoesRoute: typeof AuthenticatedPreferenciasNotificacoesRoute
  AuthenticatedResumoSemanalRoute: typeof AuthenticatedResumoSemanalRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAdminEmbaixadoresRoute: typeof AuthenticatedAdminEmbaixadoresRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPodcastsRoute: typeof AuthenticatedAdminPodcastsRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminSuporteRoute: typeof AuthenticatedAdminSuporteRoute
  AuthenticatedFerramentasChecklistRoute: typeof AuthenticatedFerramentasChecklistRoute
  AuthenticatedFerramentasConteudoRoute: typeof AuthenticatedFerramentasConteudoRoute
  AuthenticatedFerramentasDiagnosticoRoute: typeof AuthenticatedFerramentasDiagnosticoRoute
  AuthenticatedFerramentasMetaReceitaRoute: typeof AuthenticatedFerramentasMetaReceitaRoute
  AuthenticatedFerramentasPlannerRoute: typeof AuthenticatedFerramentasPlannerRoute
  AuthenticatedFerramentasWhatsappRoute: typeof AuthenticatedFerramentasWhatsappRoute
  AuthenticatedMetaIdRoute: typeof AuthenticatedMetaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAntenasRoute: AuthenticatedAntenasRoute,
  AuthenticatedAplicarDirecaoRoute: AuthenticatedAplicarDirecaoRoute,
  AuthenticatedAtividadeRoute: AuthenticatedAtividadeRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCampoMagneticoRoute: AuthenticatedCampoMagneticoRoute,
  AuthenticatedCirculoRoute: AuthenticatedCirculoRoute,
  AuthenticatedDinheiroRoute: AuthenticatedDinheiroRoute,
  AuthenticatedDirecoesRoute: AuthenticatedDirecoesRoute,
  AuthenticatedDirecoesSalvasRoute: AuthenticatedDirecoesSalvasRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImpactoRoute: AuthenticatedImpactoRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedMagnetosRoute: AuthenticatedMagnetosRoute,
  AuthenticatedMemoriaRoute: AuthenticatedMemoriaRoute,
  AuthenticatedMetasRecebidasRoute: AuthenticatedMetasRecebidasRoute,
  AuthenticatedMeuDiaRoute: AuthenticatedMeuDiaRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedPreferenciasNotificacoesRoute:
    AuthenticatedPreferenciasNotificacoesRoute,
  AuthenticatedResumoSemanalRoute: AuthenticatedResumoSemanalRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAdminEmbaixadoresRoute: AuthenticatedAdminEmbaixadoresRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPodcastsRoute: AuthenticatedAdminPodcastsRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminSuporteRoute: AuthenticatedAdminSuporteRoute,
  AuthenticatedFerramentasChecklistRoute:
    AuthenticatedFerramentasChecklistRoute,
  AuthenticatedFerramentasConteudoRoute: AuthenticatedFerramentasConteudoRoute,
  AuthenticatedFerramentasDiagnosticoRoute:
    AuthenticatedFerramentasDiagnosticoRoute,
  AuthenticatedFerramentasMetaReceitaRoute:
    AuthenticatedFerramentasMetaReceitaRoute,
  AuthenticatedFerramentasPlannerRoute: AuthenticatedFerramentasPlannerRoute,
  AuthenticatedFerramentasWhatsappRoute: AuthenticatedFerramentasWhatsappRoute,
  AuthenticatedMetaIdRoute: AuthenticatedMetaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CheckoutStripeRoute: typeof CheckoutStripeRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutRetornoRoute: CheckoutRetornoRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CheckoutStripeRoute: CheckoutStripeRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface FerramentasRouteChildren {
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingProntoRoute: typeof OnboardingProntoRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProntoRoute: OnboardingProntoRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AssinarRoute: AssinarRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FerramentasRoute: FerramentasRouteWithChildren,
  IdiomaRoute: IdiomaRoute,
  MentorRoute: MentorRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PilaresRoute: PilaresRoute,
  PlanosRoute: PlanosRoute,
  PrepararRoute: PrepararRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiMentorRoute: ApiMentorRoute,
  ApiOnboardingChatRoute: ApiOnboardingChatRoute,
  CirculosIdRoute: CirculosIdRoute,
  ModuloSlugRoute: ModuloSlugRoute,
  PagamentoConfirmandoRoute: PagamentoConfirmandoRoute,
  PagamentoLiberadoRoute: PagamentoLiberadoRoute,
  PagamentoSucessoRoute: PagamentoSucessoRoute,
  PilarSlugRoute: PilarSlugRoute,
  RCodeRoute: RCodeRoute,
  CirculosIndexRoute: CirculosIndexRoute,
  ApiPublicStripeE2eRoute: ApiPublicStripeE2eRoute,
  ApiPublicCronMagNotificationsRoute: ApiPublicCronMagNotificationsRoute,
  ApiPublicCronMarkUnconvertedReferralsRoute:
    ApiPublicCronMarkUnconvertedReferralsRoute,
  ApiPublicCronReleaseCommissionsRoute: ApiPublicCronReleaseCommissionsRoute,
  ApiPublicNotificationsOpenedRoute: ApiPublicNotificationsOpenedRoute,
  ApiPublicPaymentsInfinitepayWebhookRoute:
    ApiPublicPaymentsInfinitepayWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  ApiPublicPaymentsWebhookProviderRoute: ApiPublicPaymentsWebhookProviderRoute,
  ApiPublicPaymentsWebhookStripeRoute: ApiPublicPaymentsWebhookStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
